-- Create storage bucket for session images
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'session-images',
  'session-images',
  false,                                -- private bucket
  4194304,                              -- 4MB limit
  array['image/jpeg', 'image/png', 'image/heic']
)
on conflict (id) do nothing;

-- RLS: only the service role can read/write (backend uses service role key)
-- Mobile uploads via presigned URLs generated by the backend — no direct client access
create policy "Service role full access"
on storage.objects for all
to service_role
using (bucket_id = 'session-images');
